FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy frontend source code
COPY . .

# Expose Vite default port
EXPOSE 5173

# Run development server
CMD ["npm", "run", "dev"]
