// Configuração completa de todas as pesquisas da árvore tecnológica
export const researchTreeConfig = [
  // ===== NÍVEL 1 =====
  {
    nivel: 1,
    ramo: 'Produção',
    nome: 'Técnicas de Arado',
    icon: '🌾',
    custo: '500 Cobre, 5 Pergaminhos',
    tempoBase: '1 Dia',
    tempoMs: 86400000, // 1 dia em ms
    efeito: '+10% na produção de Comida.',
    desbloqueios: ['Aumenta produção de comida'],
  },
  {
    nivel: 1,
    ramo: 'Produção',
    nome: 'Cunhas de Madeira',
    icon: '🪵',
    custo: '500 Cobre, 5 Pergaminhos',
    tempoBase: '1 Dia',
    tempoMs: 86400000,
    efeito: '+10% na produção de Madeira.',
    desbloqueios: ['Aumenta produção de madeira'],
  },
  {
    nivel: 1,
    ramo: 'Produção',
    nome: 'Escoramento Simples',
    icon: '🪨',
    custo: '500 Cobre, 5 Pergaminhos',
    tempoBase: '1 Dia',
    tempoMs: 86400000,
    efeito: '+10% na produção de Pedra.',
    desbloqueios: ['Aumenta produção de pedra'],
  },
  {
    nivel: 1,
    ramo: 'Social',
    nome: 'Registros do Feudo',
    icon: '📖',
    custo: '800 Cobre, 10 Pergaminhos',
    tempoBase: '2 Dias',
    tempoMs: 172800000,
    efeito: '-10% no Upkeep de todas as construções.',
    desbloqueios: ['Reduz custos de manutenção'],
  },
  {
    nivel: 1,
    ramo: 'Militar',
    nome: 'Estacas Afiadas',
    icon: '♠️',
    custo: '600 Cobre, 300 Madeira',
    tempoBase: '1 Dia',
    tempoMs: 86400000,
    efeito: 'Adiciona +500 HP à Paliçada de Madeira.',
    desbloqueios: ['Fortalece defesas'],
  },
  {
    nivel: 1,
    ramo: 'Militar',
    nome: 'Milícia Básica',
    icon: '⚔️',
    custo: '1200 Cobre, 100 Ferro',
    tempoBase: '3 Dias',
    tempoMs: 259200000,
    efeito: 'Aumenta o bônus de HP do cargo Vigia para +35%.',
    desbloqueios: ['Melhora tropas'],
  },
  {
    nivel: 1,
    ramo: 'Governo',
    nome: 'Escrita Formal',
    icon: '✍️',
    custo: '2000 Cobre, 25 Pergaminhos',
    tempoBase: '4 Dias',
    tempoMs: 345600000,
    efeito: '(Final do Nv. 1) Desbloqueia a construção da Biblioteca.',
    desbloqueios: ['Biblioteca', 'Acesso a Conhecimento'],
    isFinal: true,
  },

  // ===== NÍVEL 2 =====
  {
    nivel: 2,
    ramo: 'Produção',
    nome: 'Fundamentos da Metalurgia',
    icon: '🔨',
    custo: '3.000 Cobre, 30 Perg., 500 Ferro',
    tempoBase: '5 Dias',
    tempoMs: 432000000,
    efeito: 'Desbloqueia a construção da Forja e o cargo de Ferreiro.',
    desbloqueios: ['Forja', 'Cargo: Ferreiro'],
  },
  {
    nivel: 2,
    ramo: 'Produção',
    nome: 'Carpintaria Avançada',
    icon: '🪚',
    custo: '3.000 Cobre, 30 Perg., 1000 Madeira',
    tempoBase: '5 Dias',
    tempoMs: 432000000,
    efeito: 'Desbloqueia a Marcenaria e o cargo de Carpinteiro.',
    desbloqueios: ['Marcenaria', 'Cargo: Carpinteiro'],
  },
  {
    nivel: 2,
    ramo: 'Social',
    nome: 'Hospitalidade Comunitária',
    icon: '🍺',
    custo: '2.500 Cobre, 25 Perg.',
    tempoBase: '4 Dias',
    tempoMs: 345600000,
    efeito: 'Desbloqueia a Taverna e o cargo de Taverneiro.',
    desbloqueios: ['Taverna', 'Cargo: Taverneiro'],
  },
  {
    nivel: 2,
    ramo: 'Social',
    nome: 'Domesticação de Bestas',
    icon: '🐴',
    custo: '3.500 Cobre, 35 Perg.',
    tempoBase: '5 Dias',
    tempoMs: 432000000,
    efeito: 'Desbloqueia o Estábulo e o cargo de Domador de Animais.',
    desbloqueios: ['Estábulo', 'Cargo: Domador de Animais'],
  },
  {
    nivel: 2,
    ramo: 'Social',
    nome: 'Princípios da Fé',
    icon: '⛪',
    custo: '3.000 Cobre, 30 Perg.',
    tempoBase: '5 Dias',
    tempoMs: 432000000,
    efeito: 'Desbloqueia a Igreja/Templo e o cargo de Sacerdote.',
    desbloqueios: ['Igreja/Templo', 'Cargo: Sacerdote'],
  },
  {
    nivel: 2,
    ramo: 'Militar',
    nome: 'Técnicas de Fortificação',
    icon: '🏰',
    custo: '4.000 Cobre, 1.000 Pedra',
    tempoBase: '6 Dias',
    tempoMs: 518400000,
    efeito: 'Desbloqueia o upgrade da Paliçada para Muralha de Pedra.',
    desbloqueios: ['Muralha de Pedra', 'Defesas avançadas'],
  },
  {
    nivel: 2,
    ramo: 'Governo',
    nome: 'Administração Centralizada',
    icon: '👑',
    custo: '5.000 Cobre, 50 Perg.',
    tempoBase: '7 Dias',
    tempoMs: 604800000,
    efeito: '(Final do Nv. 2) Desbloqueia a construção do Salão do Conselho.',
    desbloqueios: ['Salão do Conselho', 'Governo avançado'],
    isFinal: true,
  },

  // ===== NÍVEL 3 =====
  {
    nivel: 3,
    ramo: 'Militar',
    nome: 'Organização Militar',
    icon: '🎖️',
    custo: '8.000 Cobre, 75 Perg., 1.000 Ferro',
    tempoBase: '10 Dias',
    tempoMs: 864000000,
    efeito: 'Desbloqueia o Quartel e o cargo de Comandante Militar.',
    desbloqueios: ['Quartel', 'Cargo: Comandante Militar'],
  },
  {
    nivel: 3,
    ramo: 'Ciência',
    nome: 'Medicina e Saneamento',
    icon: '⚕️',
    custo: '7.000 Cobre, 60 Perg.',
    tempoBase: '9 Dias',
    tempoMs: 777600000,
    efeito: 'Desbloqueia o Hospital e o cargo de Médico.',
    desbloqueios: ['Hospital', 'Cargo: Médico'],
  },
  {
    nivel: 3,
    ramo: 'Ciência',
    nome: 'Fundamentos da Alquimia',
    icon: '🧪',
    custo: '7.500 Cobre, 70 Perg., 50 Ervas Raras',
    tempoBase: '9 Dias',
    tempoMs: 777600000,
    efeito: 'Desbloqueia o Laboratório de Alquimia e o cargo de Alquimista.',
    desbloqueios: ['Laboratório de Alquimia', 'Cargo: Alquimista'],
  },
  {
    nivel: 3,
    ramo: 'Economia',
    nome: 'Contabilidade Avançada',
    icon: '💰',
    custo: '6.000 Cobre, 80 Perg.',
    tempoBase: '8 Dias',
    tempoMs: 691200000,
    efeito: 'Desbloqueia o Mercado e o cargo de Mestre das Moedas.',
    desbloqueios: ['Mercado', 'Cargo: Mestre das Moedas'],
  },
  {
    nivel: 3,
    ramo: 'Engenharia',
    nome: 'Engenharia Defensiva',
    icon: '🛡️',
    custo: '12.000 Cobre, 5.000 Pedra',
    tempoBase: '14 Dias',
    tempoMs: 1209600000,
    efeito: '(Final Nv. 3) Desbloqueia upgrade para Muralhas Altas com Torres.',
    desbloqueios: ['Muralhas Altas com Torres', 'Defesas supremas'],
    isFinal: true,
  },

  // ===== NÍVEL 4 =====
  {
    nivel: 4,
    ramo: 'Engenharia',
    nome: 'Engenharia de Guerra',
    icon: '⚙️',
    custo: '20.000 Cobre, 150 Perg., 3.000 Ferro',
    tempoBase: '18 Dias',
    tempoMs: 1555200000,
    efeito: 'Desbloqueia a Oficina de Cerco e o cargo de Engenheiro.',
    desbloqueios: ['Oficina de Cerco', 'Cargo: Engenheiro'],
  },
  {
    nivel: 4,
    ramo: 'Magia',
    nome: 'Teoria Arcana de Batalha',
    icon: '✨',
    custo: '22.000 Cobre, 50 Cristais',
    tempoBase: '20 Dias',
    tempoMs: 1728000000,
    efeito: 'Desbloqueia a construção da Torre Mágica.',
    desbloqueios: ['Torre Mágica', 'Magia de batalha'],
  },
  {
    nivel: 4,
    ramo: 'Economia',
    nome: 'Rotas de Caravana',
    icon: '🚚',
    custo: '18.000 Cobre, 120 Perg.',
    tempoBase: '16 Dias',
    tempoMs: 1382400000,
    efeito: 'Desbloqueia a Casa de Comércio e o cargo de Mercador.',
    desbloqueios: ['Casa de Comércio', 'Cargo: Mercador'],
  },
  {
    nivel: 4,
    ramo: 'Espionagem',
    nome: 'Infiltração e Sabotagem',
    icon: '🗡️',
    custo: '25.000 Cobre, 200 Perg.',
    tempoBase: '21 Dias',
    tempoMs: 1814400000,
    efeito: 'Desbloqueia a Guilda de Ladrões e os cargos de Ladrão e Espião.',
    desbloqueios: ['Guilda de Ladrões', 'Cargo: Ladrão', 'Cargo: Espião'],
  },
  {
    nivel: 4,
    ramo: 'Governo',
    nome: 'Arquitetura de Bastião',
    icon: '🏯',
    custo: '30.000 Cobre, 10.000 Pedra',
    tempoBase: '28 Dias',
    tempoMs: 2419200000,
    efeito: '(Final Nv. 4) Desbloqueia upgrade para Muralhas Reforçadas.',
    desbloqueios: ['Muralhas Reforçadas', 'Poder militar máximo'],
    isFinal: true,
  },

  // ===== NÍVEL 5 =====
  {
    nivel: 5,
    ramo: 'Governo',
    nome: 'Arquitetura Soberana',
    icon: '👸',
    custo: '50.000 Cobre, 500 Perg., 2.000 Metal Raro',
    tempoBase: '40 Dias',
    tempoMs: 3456000000,
    efeito: 'Desbloqueia a construção do Castelo/Palácio.',
    desbloqueios: ['Castelo/Palácio', 'Sede do poder'],
  },
  {
    nivel: 5,
    ramo: 'Magia',
    nome: 'Cartografia Celestial',
    icon: '🌌',
    custo: '60.000 Cobre, 100 Cristais',
    tempoBase: '45 Dias',
    tempoMs: 3888000000,
    efeito: 'Desbloqueia a construção do Observatório.',
    desbloqueios: ['Observatório', 'Conhecimento cósmico'],
  },
  {
    nivel: 5,
    ramo: 'Espionagem',
    nome: 'Guerra nas Sombras',
    icon: '🌙',
    custo: '75.000 Cobre, 300 Perg.',
    tempoBase: '50 Dias',
    tempoMs: 4320000000,
    efeito: 'Desbloqueia a Câmara das Sombras e o cargo de Mestre Espião.',
    desbloqueios: ['Câmara das Sombras', 'Cargo: Mestre Espião'],
  },
  {
    nivel: 5,
    ramo: 'Cultura',
    nome: 'Doutrina de Legado [Cultural]',
    icon: '🎭',
    custo: '100.000 Cobre, 50 Artefatos',
    tempoBase: '60 Dias',
    tempoMs: 5184000000,
    efeito: '(Final do Jogo) Desbloqueia Construção de Legado Cultural.',
    desbloqueios: ['Construção de Legado Cultural', 'Vitória cultural'],
    isFinal: true,
  },
];

// Mapa de tradução: nome_display -> tech_name_backend
export const researchNameMap = {
  'Técnicas de Arado': 'tecnicas_arado',
  'Cunhas de Madeira': 'silvicultura',
  'Escoramento Simples': 'mineracao_avancada',
  'Registros do Feudo': 'registros_feudo',
  'Estacas Afiadas': 'estacas_afiadas',
  'Milícia Básica': 'milicia_basica',
  'Escrita Formal': 'escrita_formal',
  'Fundamentos da Metalurgia': 'metalurgia',
  'Carpintaria Avançada': 'carpintaria_avancada',
  'Hospitalidade Comunitária': 'hospitalidade_comunitaria',
  'Domesticação de Bestas': 'domesticacao_bestas',
  'Princípios da Fé': 'principios_fe',
  'Técnicas de Fortificação': 'tecnicas_fortificacao',
  'Administração Centralizada': 'administracao_centralizada',
  'Organização Militar': 'organizacao_militar',
  'Medicina e Saneamento': 'medicina_saneamento',
  'Fundamentos da Alquimia': 'fundamentos_alquimia',
  'Contabilidade Avançada': 'contabilidade_avancada',
  'Engenharia Defensiva': 'engenharia_defensiva',
  'Engenharia de Guerra': 'engenharia_guerra',
  'Teoria Arcana de Batalha': 'teoria_arcana',
  'Rotas de Caravana': 'rotas_caravana',
  'Infiltração e Sabotagem': 'infiltracao_sabotagem',
  'Arquitetura de Bastião': 'arquitetura_bastiao',
  'Arquitetura Soberana': 'arquitetura_soberana',
  'Cartografia Celestial': 'cartografia_celestial',
  'Guerra nas Sombras': 'guerra_sombras',
  'Doutrina de Legado [Cultural]': 'doutrina_legado',
};

// Mapa de ícones e cores por ramo
export const branchConfig = {
  Produção: { color: '#D4A574', icon: '⚙️' },
  Militar: { color: '#8B3A3A', icon: '⚔️' },
  Social: { color: '#2D5016', icon: '👥' },
  Governo: { color: '#4A4A4A', icon: '👑' },
  Ciência: { color: '#9966CC', icon: '🧬' },
  Economia: { color: '#FFD700', icon: '💰' },
  Engenharia: { color: '#FF6B6B', icon: '🔧' },
  Magia: { color: '#6B9BFF', icon: '✨' },
  Espionagem: { color: '#2C2C2C', icon: '🗡️' },
  Cultura: { color: '#FF69B4', icon: '🎭' },
};

export default researchTreeConfig;
